theme: minima
title: Bienvenidos al blog
author: nuevo-rama
email: 
description: > # this means to ignore newlines until "baseurl:"
  Descripción del blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
